name: DEV index full data dump
on:
  workflow_dispatch:
    inputs:
      release-dump:
        type: string
        description: Name of existing release dump file to index, without .zip extension (ex v1.41-2024-02-13-ror-data)
      schema-version:
        required: true
        description: Schema version to index
        type: choice
        options:
        - v2
      data-env:
        required: true
        description: ROR data env (test uses ror-data-test repo, prod uses ror-data)
        default: 'test'
        type: choice
        options:
        - test
        - prod

jobs:
  check_permission:
    runs-on: ubuntu-latest
    if: github.event.ref == 'refs/heads/dev'
    steps:
      - name: Get Permission
        uses: octokit/request-action@v3.0.0
        id: get_permission
        with:
          route: GET /repos/${{ github.repository }}/collaborators/${{ github.actor }}/permission
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: output
        run:  |
          export role_name=${{ fromJson(steps.get_permission.outputs.data).role_name }}
          if [[ "$role_name" == "admin" ]]; then
            exit 0
          else
            exit 1
          fi
  index-dump:
    runs-on: ubuntu-latest
    if: github.event.ref == 'refs/heads/dev'
    needs: check_permission
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.ref }}
      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Index dump file
        id: indexdatadump
        run: |
          cd .github/workflows
          pip install requests
          python index_dump.py -u ${{ secrets.INDEX_DUMP_DEV_API_URL_V2 }} -f ${{ github.event.inputs.release-dump }} -e  ${{ github.event.inputs.data-env }} -he ${{ secrets.INDEX_DEV_API_HEADERS }}
      - name: Notify Slack
        if: always()
        uses: slackapi/slack-github-action@v2.1.1
        with:
          webhook: ${{ secrets.CURATOR_SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            attachments:
              - color: good
                text: "DEV full index from dump status: ${{ steps.indexdatadump.outcome }}. From file: ${{ github.event.inputs.release-dump }}. Schema version: ${{ github.event.inputs.schema-version }}. Data env: ${{ github.event.inputs.data-env }}. Please check: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
