name: Create data dump
on:
  workflow_dispatch

jobs:
  generate-dump:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.ref }}
      - name: list files
        run: |
          echo | ls *