name: Deploy to Staging
on:
  push:
    branches:
      - 'staging'
env:
  MERGE_SHA: ${{ github.event.after }}
  REPO_INFO: ${{ github.event.repository.full_name }}

jobs:
  copy-files:
    runs-on: ubuntu-latest
    steps:
      - name: Do something
        run: |
          ${{ github.event.after }}
          ${{ github.event.repository.full_name }}