name: Deploy to Staging
on:
  push:
    branches:
      - 'staging'

jobs:
  copy-files:
    runs-on: ubuntu-latest
    steps:
      - name: Do something
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        run: ${{ toJson(github.event) }}