name: Deploy to Staging
on:
  push:
    branches:
      - 'staging'
env:
  MERGE_SHA: ${{ github.event.after }}
  REPO_INFO: ${{ github.event.repository.full_name }}
  BEFORE_MERGE: ${{ github.event.before  }}

jobs:
  copy-files:
    runs-on: ubuntu-latest
    steps:
      - name: Get Merge PR
        uses: octokit/request-action@v2.x
        id: get_merge_pr
        with:
          route: GET /search/issues
          q: 'repo:${{ github.event.repository.full_name }}+is:pr+is:closed+merge_sha_commit:${{ github.event.after }}'
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Get branch name
        run: |
          export url=${{ fromJson(steps.get_merge_pr.outputs.data).items[0].pull_request.url }}
          echo "release_branch=$(curl ${url} | jq .head.ref)" >> $GITHUB_ENV
      - name: checkout
        uses: actions/checkout@v2
      - name: Zip files and copy to S3
        run: |
          zip files.zip *.json
          export s3bucket_name=${{ secrets.ROR_DATA_S3_BUCKET_DEV }}
          set -e

          mkdir -p ~/.aws
          touch ~/.aws/credentials

          echo "[default]
          aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region=${{ secrets.AWS_REGION }}" > ~/.aws/credentials

          docker run --rm -it  -v ~/.aws:/root/.aws amazon/aws-cli:2.4.14 s3 ls s3://${s3bucket_name}




          