name: Deploy to Staging
on:
  push:
    branches:
      - 'staging'

jobs:
  copy-files:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: See files 
        run: |
          ls *