name: Deploy to Staging
on:
  push:
    branches:
      - 'staging'
env:
  MERGE_SHA: ${{ github.event.after }}
  REPO_INFO: ${{ github.event.repository.full_name }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

jobs:
  copy-files:
    runs-on: ubuntu-latest
    steps:
      - name: Get Merge PR
        uses: octokit/request-action@v2.x
        id: get_merge_pr
        with:
          route: GET /search/issues
          q: 'repo:${{ github.event.repository.full_name }}+is:pr+is:closed+merge_sha_commit:${{ github.event.after }}'
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Get branch name
        run: |
          export url=${{ fromJson(steps.get_merge_pr.outputs.data).items[0].pull_request.url }}
          echo "release_branch=$(curl ${url} | jq .head.ref)" >> $GITHUB_ENV
      - name: checkout
        uses: actions/checkout@v2
      - name: Zip files and copy to S3
        id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1.0.2
      - run: |
          zip files.zip *.json
          ls 
          echo aws --version




          