name: Deploy to Staging
on:
  pull_request:
    branches:
      - 'staging'
    types: [closed]

jobs:
  copy-files:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: See files 
        run: |
          ls *