name: Manual deploy to Prod
on:
  workflow_dispatch:
    inputs:
      release-tag:
        type: string
        required: true
        description: Name of the release tag that you would like to deploy to DEV
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

jobs:
  check_permission:
    runs-on: ubuntu-latest
    if: github.event.ref == 'refs/heads/main'
    steps:
      - name: Get Permission
        uses: octokit/request-action@v2.x
        id: get_permission
        with:
          route: GET /repos/${{ github.repository }}/collaborators/${{ github.actor }}/permission
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: output
        run:  |
          export role_name=${{ fromJson(steps.get_permission.outputs.data).role_name }}
          if [[ "$role_name" == "maintain"  || "$role_name" == "admin" ]]; then
            exit 0
          else
            exit 1
          fi
  copy-files:
    runs-on: ubuntu-latest
    if: github.event.ref == 'refs/heads/main'
    needs: check_permission
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: refs/tags/${{ github.event.inputs.release-tag }}
      - name: Install aws cli
        id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1.0.2
      - name: Zip and copy files
        id: copyfiles
        run: |
          cd ./${{ github.event.inputs.release-tag }}
          zip files.zip *.json
          aws s3 cp files.zip s3://${{ secrets.ROR_DATA_S3_BUCKET_DEV }}/${{ github.event.inputs.release-tag }}/files.zip
          aws s3 ls s3://${{ secrets.ROR_DATA_S3_BUCKET_DEV }}/${{ github.event.inputs.release-tag }}/files.zip
      - name: Notify Slack
        if: always()
        uses: edge/simple-slack-notify@master
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.CURATOR_SLACK_WEBHOOK_URL }}
        with:
          channel: '#ror-curation-releases'
          color: 'good'
          text: 'Copy status to dev S3 Bucket:  ${{ steps.copyfiles.outcome }}.  From directory: ${{ github.event.inputs.release-tag }}. Please check: ${env.GITHUB_SERVER_URL}/${env.GITHUB_REPOSITORY}/actions/runs/${env.GITHUB_RUN_ID}'
      - name: Index file
        id: indexdata
        run: |
          cd .github/workflows
          python -m pip install --upgrade pip
          pip install requests==2.23.0
          python index_files.py -u ${{ secrets.INDEX_DEV_API_URL }} -d ${{ github.event.inputs.release-tag }} -he ${{ secrets.INDEX_DEV_API_HEADERS }}
      - name: Notify Slack
        if: always()
        uses: edge/simple-slack-notify@master
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.CURATOR_SLACK_WEBHOOK_URL }}
        with:
          channel: '#ror-curation-releases'
          color: 'good'
          text: 'DEV index status: ${{ steps.indexdata.outcome }}. From directory: ${{ github.event.inputs.release-tag }}. Please check: ${env.GITHUB_SERVER_URL}/${env.GITHUB_REPOSITORY}/actions/runs/${env.GITHUB_RUN_ID}'

