name: Validate files
on:
  workflow_dispatch:
    inputs:
      with-relationship:
        type: boolean
        description: Check box to validate with relationships

jobs:
  validate-files:
    runs-on: ubuntu-latest
    if: github.event.ref != 'refs/heads/main'
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.ref }}
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Checkout validation suite
        uses: actions/checkout@v2
        with:
          repository: ror-community/validation-suite
          path: validation-suite
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Validate files
        id: validatefiles
        working-directory: ${{ steps.extract_branch.outputs.branch }}
        run: |
          mkdir files
          cp /*.json files/
          cd validation-suite
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          if [[ ${{ github.event.inputs.with-relationship }} == "true" ]]; then
            if [[ -f "../relationships.csv" ]]; then
              python run_validations.py -i ../files -f ../relationships.csv -p ../files/
            else
              python run_validations.py -i ../files -p ../files/
            fi
          elif [[ ${{ github.event.inputs.with-relationship }} == "false" ]]; then
            python run_validations.py -i ../files
          fi
      - name: Notify Slack
        if: always()
        uses: edge/simple-slack-notify@master
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.CURATOR_SLACK_WEBHOOK_URL }}
        with:
          channel: '#ror-curation-releases'
          color: 'good'
          text: 'Validation status:  ${{ steps.validatefiles.outcome }}. On branch: ${env.GITHUB_SERVER_URL}/${env.GITHUB_REPOSITORY}/tree/${env.GITHUB_REF_NAME} in directory ${{ github.event.inputs.release-directory }}. Please check: ${env.GITHUB_SERVER_URL}/${env.GITHUB_REPOSITORY}/actions/runs/${env.GITHUB_RUN_ID}'
